# Generated by Django 5.0.6 on 2024-07-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_amenities_roomamenities_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomstatus',
            old_name='status',
            new_name='room_status',
        ),
    ]
