# Generated by Django 5.0.6 on 2024-07-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
